In [1]:


import pandas as pd
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("../AI Generated Essays Dataset.csv")
df.tail(10)

                                                   text  generated
1450  These sources focus on the advantages of limit...          0
1451  Cars are a very big part of our lives, we rely...          0
1452  Since World War II we have been heavily depend...          0
1453  Driving cars can be a danger to humans, but al...          0
1454  studies have shown that passenger cars are res...          0
1455  There has been a fuss about the Elector Colleg...          0
1456  Limiting car usage has many advantages. Such a...          0
1457  There's a new trend that has been developing f...          0
1458  As we all know cars are a big part of our soci...          0
1459  Cars have been around since the 1800's and hav...          0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       1460 non-null   object
 1   generated  1460 non-null   int64
dtypes: int64(1), object(1)
memory usage: 22.9+ KB

In [5]:
df.isnull().sum()

text         0
generated    0
dtype: int64

In [6]:
df.to_csv('palgirism_model.csv', index=False)
df.head()

                                                text  generated
0  Machine learning, a subset of artificial intel...          1
1  A decision tree, a prominent machine learning ...          1
2  Education, a cornerstone of societal progress,...          1
3  Computers, the backbone of modern technology, ...          1
4  Chess, a timeless game of strategy and intelle...          1